name: Azure Web App Docker Compose CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.full-stack.yml build
          docker tag medplum/medplum-server karolbhandari/medplum-server:latest
          docker tag medplum/medplum-app karolbhandari/medplum-app:latest
          docker tag postgres:16 karolbhandari/postgres:16
          docker tag redis:7 karolbhandari/redis:7

      - name: Push Docker images to Docker Hub
        run: |
          docker push karolbhandari/medplum-server:latest
          docker push karolbhandari/medplum-app:latest
          docker push karolbhandari/postgres:16
          docker push karolbhandari/redis:7

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'medplum'  # Replace with your Azure Web App name
          slot-name: 'production'
          images: |
            karolbhandari/medplum-server:latest
            karolbhandari/medplum-app:latest
            karolbhandari/postgres:16
            karolbhandari/redis:7
        env:
          AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
